## numpy part-1

In [165]:
import numpy as np #표준화 되어있슴

### 1. numpy 배열(N-Dimensional Array)

In [166]:
a = np.array([1, 3, 4, 7], float)
a
#a는 넘파이의 어레이라는뜻

array([1., 3., 4., 7.])

In [167]:
a.dtype, a.shape, a.ndim, a.size
#64 double precision #default
#32 single precision

(dtype('float64'), (4,), 1, 4)

In [191]:
# Vector(1차원)
a = np.array([1, 3, 4, 7], float)
a

array([1., 3., 4., 7.])

In [169]:
#Matrix(2차원) 
b = np.array([[1, 2, 4], [4, 3, 9],[3, 7, 8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [170]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int32'), (3, 3), 2, 9)

In [171]:
#Tensor(3차원)
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [172]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [173]:
#dtype
np.array([1, 2, 3, 4], dtype=np.uint8)

array([1, 2, 3, 4], dtype=uint8)

In [174]:
# reshape
c.size

24

In [175]:
c.reshape(4,6)
#사이즈 바꾸는법 #size가 같으면 reshapdl 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [176]:
c.reshape(3, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [177]:
c.reshape(3, -1, 4)
# 평면이 4ㄱ개, 행이 3개, 열이 4개인 텐서

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [178]:
a.reshape(4, -1)

array([[1.],
       [3.],
       [4.],
       [7.]])

In [179]:
a.reshape(-1, 4)

array([[1., 3., 4., 7.]])

In [180]:
b.reshape(-1,)
#하나여도 ","를 붙여서 표기해야함

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [181]:
b.flatten()
#값을 하나로 펼쳐줌

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and Slicing

In [189]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
a[1][1], a[1][1], a[-1][-2]
#리스트에서는 허용하지 않지만 넘파이에서는 가능하다.

(5, 5, 5)

In [ ]:
a[1, :2]

array([4, 5])

In [ ]:
a[:,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
b[:2,1:]

array([[2, 4],
       [3, 9]])

In [ ]:
b[1:,:2]

array([[4, 3],
       [3, 7]])

In [ ]:
b[:2, ::2]

array([[1, 4],
       [4, 9]])

### 3. 배열 생성

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,4.1,0.5)


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
l = np.arange(1,4.1,0.5).tolist()
l
#파이썬 넘파이에서 실수로 리스트를 만드는방법

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

In [ ]:
np.arange(-2,2.01,0.01).size

401

In [ ]:
#linear space
np.linspace(-2, 2, 201).size

201

- ones, zeros, empty

In [ ]:
np.ones(shape=(10,), dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [ ]:
np.ones((2, 4))
#기본이 실수형이다.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros(4)
#스펠링 조심할것

array([0., 0., 0., 0.])

In [ ]:
np.empty(4)
#empty특)값을 초기화하지말고 값을 저장할 공간만 만든다.

array([0., 0., 0., 0.])

- 대각선: identity, eye

In [192]:
# 정방형 (n X n))
np.identity(3, dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [ ]:
#직사각형 모양(N X N)
np.eye(N=3, M=5, dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [ ]:
np.eye(3, 5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

- 데이터 분포에 따른 random sampling

In [ ]:
np.random.seed(2021)

In [ ]:
np.random.random(4)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308])

In [ ]:
np.random.normal(10, 4, 4)

array([12.22350333,  7.17798285, 14.52343305, 12.58000735])