# 3 Numpy - Part 2

### 4-. Operation

In [6]:
import numpy as np

In [9]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a.sum()

78

In [13]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [14]:
a.sum(axis=1)

array([10, 26, 42])

In [15]:
np.sum(a[0])

10

- sorting

In [17]:
b = np.array([[4,3,5,7], [1, 12, 11, 9], [2, 5, 1, 14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [19]:
np.sort(b) #axis=1, ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [20]:
b.sort()

In [21]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [22]:
np.sort(b, axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [23]:
#내림차순일 경우에는 아래와 같은 방법으로
c = np.array([42, 38, 12, 25])
np.sort(c)[::1]

array([12, 25, 38, 42])

In [24]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [25]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [26]:
c[[2, 3, 1, 0]]

array([12, 25, 38, 42])

- Mathematical function

In [28]:
def sigmoid(x):
    return 1./(1+np.exp(-x))

In [30]:
xs = np.array([-10, 0, 10])
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

In [31]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [34]:
b.T
#행과 열을 바꿔치기(전치행렬) #T : Transpose를 의미한다.

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate.vstack.hstack

In [36]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [38]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [39]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

- array operation 

In [42]:
a + a

array([[2, 4],
       [6, 8]])

In [43]:
a - a

array([[0, 0],
       [0, 0]])

In [44]:
a * a 

array([[ 1,  4],
       [ 9, 16]])

In [45]:
a / a

array([[1., 1.],
       [1., 1.]])

- broadcasting

In [46]:
a + 3

array([[4, 5],
       [6, 7]])

- dot prouct

In [53]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [54]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [56]:
a.dot(b)
#GPU가 잘함

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5. Comparison

- All & Any

In [60]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.any(a>5), np.all(a>5)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [65]:
np.any(a>5), np.all(a>5)

(True, False)

- Logical operation

In [67]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [68]:
np.logical_or(a < 3, a > 7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

_ argumax, argmin

In [71]:
np.argmax(a), np.argmin(a) 

(9, 0)

### 6. Bloolean & Fancy index

In [73]:
a[b]

array([4, 5, 6])

In [74]:
a[np.logical_or(a < 3, a >7)]

array([0, 1, 2, 8, 9])

In [75]:
a[a > 5]

array([6, 7, 8, 9])

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [78]:
a[[3, 5, 7,3]]

array([3, 5, 7, 3])

### 7. 기술통계

In [80]:
a = np.random.randn(10)
a

array([ 3.08091312, -0.82245198, -1.93173059,  0.57016824,  0.3567617 ,
        0.33020922,  2.64650098,  1.53513496, -0.81087966, -1.01185064])

In [81]:
a.mean(), np.mean(a)

(0.3942775361578619, 0.3942775361578619)

In [83]:
# 표준 편차(standard devitation)
a.std(), np.std(a)

(1.54754229258587, 1.54754229258587)

In [84]:
a.max(), a.min()

(3.0809131248157997, -1.931730591409336)

In [87]:
# 4분위수
np.percentile(a, 0)

-1.931730591409336

In [90]:
np.percentile(a, 25), np.percentile(a, 75)

(-0.8195589019224803, 1.293893281068056)

In [92]:
np.percentile(a, 50), np.median(a)

(0.34348546091182397, 0.34348546091182397)

In [93]:
# 집단의 크기
np. random.randn(1000)
c = np.random.randn(100000)

In [94]:
b.mean(), c.mean()

(0.3, -0.0016513926473535633)

In [96]:
b.std(), c.std()

(0.45825756949558394, 1.0012108778321223)