# 3 Numpy - Part 2

### 4-. Operation

In [3]:
import numpy as np

In [4]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
a.sum()

78

In [57]:
a.sum(axis=0)

array([ 0.41349385, -0.32925354, -1.3912267 , -2.73262869,  2.62333902])

In [7]:
a.sum(axis=1)

array([10, 26, 42])

In [8]:
np.sum(a[0])

10

- sorting

In [9]:
b = np.array([[4,3,5,7], [1, 12, 11, 9], [2, 5, 1, 14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [10]:
np.sort(b) #axis=1, ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [11]:
b.sort()

In [12]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [13]:
np.sort(b, axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [14]:
#내림차순일 경우에는 아래와 같은 방법으로
c = np.array([42, 38, 12, 25])
np.sort(c)[::1]

array([12, 25, 38, 42])

In [15]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [16]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [17]:
c[[2, 3, 1, 0]]

array([12, 25, 38, 42])

- Mathematical function

In [18]:
def sigmoid(x):
    return 1./(1+np.exp(-x))

In [19]:
xs = np.array([-10, 0, 10])
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

In [20]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [21]:
b.T
#행과 열을 바꿔치기(전치행렬) #T : Transpose를 의미한다.

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate.vstack.hstack

In [22]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [23]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [24]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

- array operation 

In [26]:
a + a

array([[2, 4],
       [6, 8]])

In [27]:
a - a

array([[0, 0],
       [0, 0]])

In [28]:
a * a 

array([[ 1,  4],
       [ 9, 16]])

In [29]:
a / a

array([[1., 1.],
       [1., 1.]])

- broadcasting

In [30]:
a + 3

array([[4, 5],
       [6, 7]])

- dot prouct

In [31]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [32]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [33]:
a.dot(b)
#GPU가 잘함

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5. Comparison

- All & Any

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.any(a>5), np.all(a>5)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [37]:
np.any(a>5), np.all(a>5)

(True, False)

- Logical operation

In [38]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [39]:
np.logical_or(a < 3, a > 7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

_ argumax, argmin

In [40]:
np.argmax(a), np.argmin(a) 

(9, 0)

### 6. Bloolean & Fancy index

In [41]:
a[b]

array([4, 5, 6])

In [42]:
a[np.logical_or(a < 3, a >7)]

array([0, 1, 2, 8, 9])

In [43]:
a[a > 5]

array([6, 7, 8, 9])

In [44]:
a[[3, 5, 7,3]]

array([3, 5, 7, 3])

### 7. 기술통계

In [56]:
a = np.random.randn(5, 6,10)
a

array([[ 2.31135003e-01,  7.95658909e-01, -1.01318399e+00,
         1.19605797e+00, -1.31866574e+00],
       [ 3.93628435e-01,  1.45889793e+00,  9.70677482e-01,
         3.08849511e-01, -4.89770262e-04],
       [ 4.83668250e-01, -3.69272333e-02, -6.49247458e-01,
        -1.42142342e-01,  1.19631209e+00],
       [-1.49503325e+00, -1.40615953e+00, -8.01266343e-01,
        -6.99878998e-01,  3.01671420e-01],
       [ 1.07218049e+00, -8.88692287e-01,  1.02089238e-01,
        -9.82083771e-01,  3.80907031e+00],
       [-2.72085077e-01, -2.52031332e-01, -2.95633837e-04,
        -2.41343105e+00, -1.36455929e+00]])

In [46]:
a.mean(), np.mean(a)

(-0.1789367573576043, -0.1789367573576043)

In [47]:
# 표준 편차(standard devitation)
a.std(), np.std(a)

(1.024184180101418, 1.024184180101418)

In [48]:
a.max(), a.min()

(2.432739229153965, -3.5733299250934003)

In [49]:
# 4분위수
np.percentile(a, 0)

-3.5733299250934003

In [50]:
np.percentile(a, 25), np.percentile(a, 75)

(-0.8405534605826259, 0.4857969980158619)

In [51]:
np.percentile(a, 50), np.median(a)

(-0.14986307775461402, -0.14986307775461402)

In [52]:
# 집단의 크기
np. random.randn(1000)
c = np.random.randn(100000)

In [53]:
b.mean(), c.mean()

(0.3, -0.0017910648986670026)

In [54]:
b.std(), c.std()

(0.45825756949558394, 1.000448545430933)