In [4]:
import numpy as np

In [5]:
#Q.1
b = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [6]:
#Q.2 

m = np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
#2-1
m[1][2]


7

In [8]:
#2-2
m[2][4]


14

In [9]:
#2-3
m [1,1:3:]

array([6, 7])

In [10]:
#2-4
m [1:,2] 

array([ 7, 12])

In [11]:
#2-5
m [:2,3:],

(array([[3, 4],
        [8, 9]]),)

In [28]:
#Q3
m = np.arange(0,15).reshape(3,5)
m.flatten
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
#3-1
m[m % 3 == 0]


array([ 0,  3,  6,  9, 12])

In [14]:
#3-2
m[m % 4 == 1]


array([ 1,  5,  9, 13])

In [30]:
#3-3
m[(m % 3 == 0) &  (m % 4 == 1)]

array([9])

In [35]:
#3-3//2
m[np.logical_and(m%3==0, m%4==1)]

array([9])

In [41]:
#Q.4
xros = 2 * np.identity(n=5, dtype = int) + 1 * np.eye(5, 5, k=1, dtype = int) +  3 * np.eye(5, 5, k=-1, dtype = int)
xros

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [49]:
#Q.5
np.random.seed(2021)
z = np.random.uniform(0, 10, 30).reshape(6,5).round(4)
z

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724],
       [1.2816, 1.7899, 7.5293, 6.6216, 7.8431],
       [0.9689, 0.5857, 9.624 , 6.1656, 0.8663],
       [5.6127, 6.1652, 9.6384, 5.743 , 3.7116],
       [4.5215, 2.0185, 5.6931, 1.951 , 5.837 ],
       [4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [44]:
#5-1
z.max()

9.972432813403188

In [45]:
#5-2
z.sum(axis=1)

array([27.88211162, 25.06551557, 18.21049076, 30.87105237, 20.021006  ,
       26.1850781 ])

In [50]:
#5-3
z.max(axis=1)

array([9.9724, 7.8431, 9.624 , 9.6384, 5.837 , 8.231 ])

In [22]:
#5-4
z.mean(axis=1)

array([3.65690263, 4.5286052 , 5.81084444, 4.79334712, 1.06368185,
       5.09071057])

In [51]:
#5-5
z.min(axis=1)

array([1.3895, 1.2816, 0.5857, 3.7116, 1.951 , 0.6906])

In [24]:
#Q.6
eng = np.array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])

In [52]:
np.hstack([eng.T])

array([[  1,  46,  81],
       [  2,  99,  59],
       [  3, 100,  90],
       [  4,  71, 100]])

In [55]:
indices = np.argsort(eng[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [56]:
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [59]:
#모든행을 영어성적 내림차순으로 정렬
eng[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [58]:
#한줄
eng[:, np.argsort(eng[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [26]:
# Q.7

import random 
result=[1]*6 
for i in range(100): 
    dice=random.randint(1,6)
    result[dice-1] += 1 

for idx,i in enumerate(result): 
    print(idx,'-',i,'번,',end=' ')

np.mean(idx * i)


0 - 15 번, 1 - 21 번, 2 - 17 번, 3 - 18 번, 4 - 18 번, 5 - 17 번, 

85.0

In [65]:

#주사위 백번
np.random.seed(2021)
dice = np.random.randint(1, 7, 100)
np.mean(dice)


3.7

In [67]:
#dice array에서 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [76]:
#dice array에서 고유값 및 그 갯수
np.unique(dice, return_counts+True)

NameError: name 'return_counts' is not defined

In [78]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

In [86]:
# Q.8
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')


10149 10218 10175 10093 10149 

In [100]:
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 5)
price = 10000
price_list = []
for i in range(500):
    price = price + np.round(price*rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [99]:
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])