In [519]:
import numpy as np

In [520]:
#Q.1
b = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [521]:
#Q.2 

m = np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [522]:
#2-1
m[1][2]


7

In [523]:
#2-2
m[2][4]


14

In [524]:
#2-3
m [1,1:3:]

array([6, 7])

In [525]:
#2-4
m [1:,2] 

array([ 7, 12])

In [526]:
#2-5
m [:2,3:]

array([[3, 4],
       [8, 9]])

In [527]:
#Q3
m = np.arange(0,15).reshape(3,5)
m.flatten
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [530]:
#3-1
m * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [538]:
#3-2
m / 4 == 1

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [558]:
#3-3
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [578]:
np.eye(5, 5, k=1,dtype=np.int16)
np.


array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=int16)

In [579]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>