In [7]:
import numpy as np

In [8]:
#Q.1
b = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [9]:
#Q.2 

m = np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
#2-1
m[1][2]


7

In [11]:
#2-2
m[2][4]


14

In [12]:
#2-3
m [1,1:3:]

array([6, 7])

In [13]:
#2-4
m [1:,2] 

array([ 7, 12])

In [14]:
#2-5
m [:2,3:]

array([[3, 4],
       [8, 9]])

In [31]:
#Q3
m = np.arange(0,15).reshape(3,5)
m.flatten
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
#3-1
m * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [38]:
#3-2
m[m % 4 == 1]


array([ 1,  5,  9, 13])

In [39]:
#3-3
m[(m % 3 == 0) & (m % 4 == 1)]

array([9])

In [68]:
#Q.4


array([], shape=(3, 2, 1, 0, 0, 0), dtype=int32)

In [168]:
#Q.5
실수 리스트트

SyntaxError: invalid syntax (<ipython-input-168-7e5b27a1d61d>, line 2)

In [139]:
a.sum()

1

In [132]:
#Q.6
a = np.array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])

In [128]:
np.hstack([eng.T])

array([[  1,  46,  81],
       [  2,  99,  59],
       [  3, 100,  90],
       [  4,  71, 100]])

In [123]:
# Q.7

import random 
result=[1]*6 
for i in range(100): 
    dice=random.randint(1,6)
    result[dice-1] += 1 

for idx,i in enumerate(result): 
    print(idx,'-',i,'번,',end=' ')

np.mean(idx * i)


0 - 27 번, 1 - 13 번, 2 - 16 번, 3 - 15 번, 4 - 21 번, 5 - 14 번, 

70.0

In [129]:
# Q.8


