In [258]:
import numpy as np

In [259]:
#Q.1
b = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [260]:
#Q.2 

m = np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [261]:
#2-1
m[1][2]


7

In [262]:
#2-2
m[2][4]


14

In [263]:
#2-3
m [1,1:3:]

array([6, 7])

In [264]:
#2-4
m [1:,2] 

array([ 7, 12])

In [265]:
#2-5
m [:2,3:]

array([[3, 4],
       [8, 9]])

In [266]:
#Q3
m = np.arange(0,15).reshape(3,5)
m.flatten
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [267]:
#3-1
m * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [268]:
#3-2
m[m % 4 == 1]


array([ 1,  5,  9, 13])

In [269]:
#3-3
m[(m % 3 == 0) &  (m % 4 == 1)]

array([9])

In [270]:
#Q.4
xros = 2 * np.identity(n=5) + 1 * np.eye(5, 5, k=1) +  3 * np.eye(5, 5, k=-1)
print(xros)

[[2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [0. 3. 2. 1. 0.]
 [0. 0. 3. 2. 1.]
 [0. 0. 0. 3. 2.]]


In [275]:
import random

In [277]:
#Q.5
z = np.random.uniform(0, 10, 30).reshape(6,5)
z

array([[8.32084761, 0.13458558, 5.09335392, 4.795487  , 0.29654941],
       [0.11428527, 3.31844   , 0.61431079, 5.98173508, 8.85920254],
       [4.12133775, 0.38272199, 0.80842404, 0.81914542, 8.09367334],
       [8.00694003, 0.16909811, 8.61294325, 9.11300224, 4.00876685],
       [2.86890698, 8.43044885, 6.17044553, 1.40598727, 2.28755614],
       [8.41497971, 8.44358474, 2.20145993, 8.1113764 , 5.35953534]])

In [278]:
#5-1
z.max()

9.113002243524484

In [279]:
#5-2
z.sum(axis=1)

array([18.64082352, 18.88797367, 14.22530254, 29.91075048, 21.16334477,
       32.53093612])

In [280]:
#5-3
z.max(axis=1)

array([8.32084761, 8.85920254, 8.09367334, 9.11300224, 8.43044885,
       8.44358474])

In [281]:
#5-4
z.mean(axis=1)

array([3.7281647 , 3.77759473, 2.84506051, 5.9821501 , 4.23266895,
       6.50618722])

In [282]:
#5-5
z.min(axis=1)

array([0.13458558, 0.11428527, 0.38272199, 0.16909811, 1.40598727,
       2.20145993])

In [ ]:
#Q.6
eng = np.array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])

In [ ]:
np.hstack([eng.T])

array([[  1,  46,  81],
       [  2,  99,  59],
       [  3, 100,  90],
       [  4,  71, 100]])

In [ ]:
# Q.7

import random 
result=[1]*6 
for i in range(100): 
    dice=random.randint(1,6)
    result[dice-1] += 1 

for idx,i in enumerate(result): 
    print(idx,'-',i,'번,',end=' ')

np.mean(idx * i)


0 - 15 번, 1 - 20 번, 2 - 18 번, 3 - 14 번, 4 - 17 번, 5 - 22 번, 

110.0

In [283]:
# Q.8
pass
